// Host-side image loading helper — used by VLM ports.
// Auto-generated by scaffoldTs.ts -- do not edit manually after scaffold.
//
// Reads an image file (PNG / JPEG / BMP) into a flat uint8 RGB buffer
// using stb_image (single-header, no link dependency).
//
// Vendoring is automatic: the CMakeLists.txt scaffold fetches stb headers
// via FetchContent on first build and adds the source dir to the include
// path. The matching src/third_party/stb_image_impl.cpp (also scaffolded)
// defines STB_IMAGE_IMPLEMENTATION in exactly one TU. The agent does NOT
// need to download or commit stb headers.
//
// Why stb_image rather than OpenCV / libjpeg / libpng:
//   - Single header, zero linker dependencies — compiles cleanly on
//     Android NDK without extra libraries.
//   - PNG + JPEG + BMP + GIF in ~3000 lines of public-domain C.
//   - Matches PyTorch torchvision's `read_image()` output layout exactly
//     when using `image_array[:, :, :3]` (RGB, uint8, HWC).
//
// API:
//   bool load_image_rgb_u8(const std::string& path, ImageBufferU8& out)
//      → fills out.data (HWC uint8), out.H, out.W, out.C=3. Returns false
//        on any I/O or decode error (sets out.error to a human-readable
//        message). Forces channels=3 even if the source is RGBA or
//        grayscale (RGBA → drops alpha; grayscale → broadcasts to RGB).

#pragma once

#include <cstdint>
#include <string>
#include <vector>

#include "stb_image.h"

struct ImageBufferU8 {
    std::vector<uint8_t> data;   // [H * W * 3], HWC, row-major
    int H = 0;
    int W = 0;
    int C = 3;                   // always 3 — caller code is RGB-only
    std::string error;           // empty when load succeeded
};

inline bool load_image_rgb_u8(const std::string& path, ImageBufferU8& out) {
    int w = 0, h = 0, channels_in_file = 0;
    // Force 3-channel output (req_comp=3): stb handles RGBA → RGB drop
    // and grayscale → RGB broadcast for us.
    unsigned char* pixels = stbi_load(path.c_str(), &w, &h, &channels_in_file, 3);
    if (!pixels) {
        out.error = std::string("stbi_load failed for '") + path + "': " + (stbi_failure_reason() ? stbi_failure_reason() : "unknown error");
        return false;
    }
    out.H = h;
    out.W = w;
    out.C = 3;
    out.data.assign(pixels, pixels + (h * w * 3));
    stbi_image_free(pixels);
    out.error.clear();
    return true;
}
