// Image patchify kernel — used by VLM ports (SigLIP / ViT-style).
// Auto-generated by scaffoldTs.ts -- do not edit manually after scaffold.
//
// Splits a normalized CHW image into a sequence of flattened patches that
// the ViT's patch_embed Conv2d would otherwise produce. SigLIP-style
// vision towers always use a single big conv to do this; the simpler
// reshape kernel below produces equivalent input shape for downstream
// matmul-based patch projection. The agent decides which path to use
// based on what's in modeling_*.py:
//
//   - If `patch_embed` is `nn.Conv2d(3, hidden, patch_size, stride=patch_size)`:
//     either (a) emit a Conv2d kernel OR (b) use THIS kernel to reshape
//     into [N_patches, 3 * patch_size * patch_size] and then do a single
//     matmul with the flattened conv weights (mathematically identical,
//     usually faster).
//   - If `patch_embed` is already linear (rare): skip this kernel.
//
// Output layout:
//   patches[p, k] where p ∈ [0, N_patches), k ∈ [0, 3 * patch_size²).
//   patches.shape = [N_patches, 3 * patch_size²].
//   N_patches = (H / patch_size) * (W / patch_size).
//
// Patch ordering is row-major (top-left → top-right → next row), matching
// PyTorch ViT.flatten(2).transpose(1, 2).
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif


__kernel void image_patchify(
    __global const storage_t* image,  // [3, H, W] CHW (after image_normalize)
    __global storage_t* patches,      // [N_patches, 3 * patch_size * patch_size]
    const int H,
    const int W,
    const int patch_size) {

    int p = get_global_id(0);  // patch index ∈ [0, N_patches)
    int k = get_global_id(1);  // intra-patch flat index ∈ [0, 3 * patch_size * patch_size)
    int pps2 = 3 * patch_size * patch_size;
    int Wp = W / patch_size;
    int Hp = H / patch_size;
    int N_patches = Hp * Wp;
    if (p >= N_patches || k >= pps2) return;

    // Decode (channel, dy, dx) from k. Channel-fastest ordering (matches
    // PyTorch's tensor.permute(0, 2, 3, 1).flatten(1, 2).flatten(-2)).
    int dy = k / (patch_size * 3);
    int rem = k % (patch_size * 3);
    int dx = rem / 3;
    int c = rem % 3;

    int patch_row = p / Wp;
    int patch_col = p % Wp;
    int src_h = patch_row * patch_size + dy;
    int src_w = patch_col * patch_size + dx;
    int hw = H * W;

    float v = LOAD(image, c * hw + src_h * W + src_w);
    STORE(patches, p * pps2 + k, v);
}
