// Image resize kernel (bilinear interpolation) — used by VLM ports.
// Auto-generated by scaffoldTs.ts -- do not edit manually after scaffold.
//
// Resizes an RGB image (uint8, HWC layout) to a target (H_out, W_out).
// Bilinear interpolation; channel-major loop. Each work-item produces
// one output pixel's 3 channels.
//
// Parameters:
//   src:      [H_in * W_in * 3] uint8   — input image (RGB interleaved)
//   dst:      [H_out * W_out * 3] uint8 — output image (RGB interleaved)
//   H_in, W_in, H_out, W_out: source + target dimensions
//
// FP16 RULE — this kernel operates on uint8 pixel values throughout; no
// fp16/fp32 ambiguity. The output is uint8 because image_normalize
// (which runs next) consumes uint8 and produces fp32/fp16 normalized.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif


__kernel void image_resize(
    __global const unsigned char* src,    // [H_in, W_in, 3] uint8
    __global unsigned char* dst,          // [H_out, W_out, 3] uint8
    const int H_in,
    const int W_in,
    const int H_out,
    const int W_out) {

    int gx = get_global_id(0);  // column in dst
    int gy = get_global_id(1);  // row in dst
    if (gx >= W_out || gy >= H_out) return;

    // Map dst pixel (gy, gx) to src space via reciprocal scaling.
    // Use the "align_corners=False" convention (HF default for vision models).
    float fy = ((float)gy + 0.5f) * (float)H_in / (float)H_out - 0.5f;
    float fx = ((float)gx + 0.5f) * (float)W_in / (float)W_out - 0.5f;

    int y0 = (int)floor(fy);
    int x0 = (int)floor(fx);
    int y1 = y0 + 1;
    int x1 = x0 + 1;
    float wy = fy - (float)y0;
    float wx = fx - (float)x0;

    // Clamp to source bounds (replication padding).
    y0 = max(0, min(H_in - 1, y0));
    y1 = max(0, min(H_in - 1, y1));
    x0 = max(0, min(W_in - 1, x0));
    x1 = max(0, min(W_in - 1, x1));

    int dst_base = (gy * W_out + gx) * 3;
    for (int c = 0; c < 3; c++) {
        float p00 = (float)src[(y0 * W_in + x0) * 3 + c];
        float p01 = (float)src[(y0 * W_in + x1) * 3 + c];
        float p10 = (float)src[(y1 * W_in + x0) * 3 + c];
        float p11 = (float)src[(y1 * W_in + x1) * 3 + c];
        float v = (1.0f - wy) * ((1.0f - wx) * p00 + wx * p01)
                + wy        * ((1.0f - wx) * p10 + wx * p11);
        dst[dst_base + c] = (unsigned char)clamp(v + 0.5f, 0.0f, 255.0f);
    }
}
