// Splice image tokens into the LM embedding sequence — VLM port load-bearing.
// Auto-generated by scaffoldTs.ts -- do not edit manually after scaffold.
//
// The VLM tokenizer produces a single `image_token_id` placeholder
// (idefics3: 49190; LLaVA: -200; varies per model). This kernel REPLACES
// that placeholder with N image feature vectors from the projector output.
//
// Inputs:
//   text_embeds:    [T_in, D] storage_t   — LM-embedding(token_ids) where
//                                            one position holds the embedding
//                                            for image_token_id.
//   image_features: [N, D]   storage_t   — projector output for the image
//                                            (already projected to LM dim).
//   placeholder_pos: int                   — index of image_token_id in the
//                                            text_embeds row dimension.
//   out:            [T_out, D] storage_t  — output sequence; T_out = T_in - 1 + N.
//   T_in, N, D                             — dimensions.
//
// Layout: out is a row-major concatenation
//   out[0:placeholder_pos]                = text_embeds[0:placeholder_pos]
//   out[placeholder_pos:placeholder_pos+N] = image_features
//   out[placeholder_pos+N:]               = text_embeds[placeholder_pos+1:T_in]
//
// EDGE CASES the agent MUST handle in host C++:
//   - Multi-image (>1 placeholder occurrence): call this kernel once per
//     placeholder, walking left-to-right. The placeholder index shifts
//     by (N-1) per splice.
//   - Pixel-shuffle adjustment: SmolVLM/idefics3 use scale_factor=2 → N is
//     P/4 where P is the patchify count. Caller passes the final N.
//
// FAILURE MODE — if T_out is wrong (caller miscomputed), the LM ingests
// garbage and the caption collapses. Compute T_out = T_in - 1 + N exactly
// once, in host code, and assert it matches the allocated out buffer.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif


__kernel void splice_image_tokens(
    __global const storage_t* text_embeds,    // [T_in, D]
    __global const storage_t* image_features, // [N, D]
    __global storage_t* out,                  // [T_out, D] where T_out = T_in - 1 + N
    const int T_in,
    const int N,
    const int D,
    const int placeholder_pos) {

    int t = get_global_id(0);  // output row index
    int d = get_global_id(1);  // hidden dim index
    int T_out = T_in - 1 + N;
    if (t >= T_out || d >= D) return;

    float v;
    if (t < placeholder_pos) {
        // pre-image text: copy from text_embeds[t]
        v = LOAD(text_embeds, t * D + d);
    } else if (t < placeholder_pos + N) {
        // image feature region: copy from image_features[t - placeholder_pos]
        int img_idx = t - placeholder_pos;
        v = LOAD(image_features, img_idx * D + d);
    } else {
        // post-image text: copy from text_embeds[t - (N - 1)]
        int text_idx = t - (N - 1);
        v = LOAD(text_embeds, text_idx * D + d);
    }
    STORE(out, t * D + d, v);
}
