// BONSAI_NO_FMA: disable fp contraction for bit-consistent fp32 across
// GPUs (Adreno mad-fusion flips near-tie logits vs the CPU oracle).
#ifdef BONSAI_NO_FMA
#pragma OPENCL FP_CONTRACT OFF
#endif
// Utility kernels shared across the model.
// Auto-generated by scaffoldTs.ts -- do not edit manually.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif

// Element-wise add: a[i] += b[i]. Operates on activation buffers (storage_t).
// Internal arithmetic in float so fp16 storage doesn't lose precision on
// long residual chains (residual stream variance shrinks otherwise).
//
// Vec4 fp16 path: 1 thread emits 4 contiguous fp16. Dispatch with
// gws = n/4 when caller knows n % 4 == 0 (HIDDEN_SIZE=896 ✓).
// Falls through to scalar tail elements (won't execute on Qwen).
__kernel void element_add(__global storage_t* a,
                          __global const storage_t* b,
                          const int n) {
    int gid = (int)get_global_id(0);
#ifdef USE_FP16
    const int n4 = n >> 2;
    if (gid < n4) {
        __global half* ah = (__global half*)a;
        __global const half* bh = (__global const half*)b;
        float4 av = vload_half4(gid, ah);
        float4 bv = vload_half4(gid, bh);
        vstore_half4(av + bv, gid, ah);
        return;
    }
    // Scalar tail (only fires if dispatch passes more groups than n4).
    const int tail_idx = (gid - n4) + n4 * 4;
    if (tail_idx < n) {
        float av = LOAD(a, tail_idx);
        float bv = LOAD(b, tail_idx);
        STORE(a, tail_idx, av + bv);
    }
#else
    if (gid < n) {
        float av = LOAD(a, gid);
        float bv = LOAD(b, gid);
        STORE(a, gid, av + bv);
    }
#endif
}

