// Auto-generated by scaffoldTs.ts -- do not edit manually.
// Graph-mode RoPE helper. Computes cos/sin tables on demand and caches them
// across calls. Safe for any rotary-attention model (Llama, Qwen, Mistral,
// OpenELM, etc.) — head_dim and theta_base are passed at call time, not
// baked at scaffold time.
//
// Usage from src/ops/attention.cpp:
//
//   cl_mem cos = nullptr, sin = nullptr;
//   if (!nnopt_get_rotary_tables(cl_ctx,
//                                MODEL_CONFIG::MAX_POSITION_EMBEDDINGS,
//                                MODEL_CONFIG::HEAD_DIM,
//                                (float)MODEL_CONFIG::ROPE_THETA,
//                                cos, sin)) {
//       NNOPT_ERROR("rotary tables unavailable");
//       return nullptr;
//   }
//   // Use cos/sin in kernels/rope.cl. DO NOT clReleaseMemObject(cos/sin) —
//   // the helper owns them and reuses them across every layer/step.

#pragma once

#define CL_TARGET_OPENCL_VERSION 120
#include <CL/cl.h>

class OpenCLContext;

bool nnopt_get_rotary_tables(OpenCLContext& cl_ctx,
                              int max_seq_len,
                              int head_dim,
                              float theta_base,
                              cl_mem& cos_out,
                              cl_mem& sin_out);

// fp32 variant: cos/sin stored as raw float (NO fp16 roundtrip). The Gemma3
// reference computes RoPE in fp32; storing the tables fp16 loses ~2.4e-4 per
// element which accumulates through the sliding-window (short-wavelength) RoPE
// layers. The rope_f32 kernel reads these as __global const float*.
bool nnopt_get_rotary_tables_f32(OpenCLContext& cl_ctx,
                                  int max_seq_len,
                                  int head_dim,
                                  float theta_base,
                                  cl_mem& cos_out,
                                  cl_mem& sin_out);
