// Image normalize kernel — used by VLM ports.
// Auto-generated by scaffoldTs.ts -- do not edit manually after scaffold.
//
// Converts uint8 RGB pixels to normalized fp32/fp16 in CHW (channel-first)
// layout matching what the vision tower expects:
//
//   out[c, h, w] = ((src[h, w, c] / 255.0) - mean[c]) / std[c]
//
// SigLIP / CLIP defaults: mean = std = [0.5, 0.5, 0.5] → output in [-1, 1].
// ImageNet defaults:      mean = [0.485, 0.456, 0.406], std = [0.229, 0.224, 0.225].
// Read mean/std from the model's `preprocessor_config.json` (image_mean +
// image_std fields) — do NOT hardcode.
//
// Parameters:
//   src:      [H, W, 3] uint8         — HWC layout (after image_resize)
//   dst:      [3, H, W] storage_t     — CHW layout (vision tower input)
//   H, W:     image dimensions
//   mean_r/g/b, std_r/g/b: per-channel normalization stats (host-side floats)
//
// FP16 RULE — normalization arithmetic is fp32 even on the fp16 build
// path. STORE() routes the final write through vstore_half / raw indexing
// per the dtype-template macro.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif


__kernel void image_normalize(
    __global const unsigned char* src,    // [H, W, 3] uint8
    __global storage_t* dst,              // [3, H, W] storage_t (CHW)
    const int H,
    const int W,
    const float mean_r, const float mean_g, const float mean_b,
    const float std_r,  const float std_g,  const float std_b) {

    int gx = get_global_id(0);  // column
    int gy = get_global_id(1);  // row
    if (gx >= W || gy >= H) return;

    const int hw = H * W;
    int src_base = (gy * W + gx) * 3;
    int dst_offset = gy * W + gx;

    float r = ((float)src[src_base + 0] / 255.0f - mean_r) / std_r;
    float g = ((float)src[src_base + 1] / 255.0f - mean_g) / std_g;
    float b = ((float)src[src_base + 2] / 255.0f - mean_b) / std_b;

    STORE(dst, 0 * hw + dst_offset, r);
    STORE(dst, 1 * hw + dst_offset, g);
    STORE(dst, 2 * hw + dst_offset, b);
}
