// Reference: model_info/transformers_src/modeling_mamba2.py:Mamba2Mixer.torch_forward ("SSM transformation" for both prefill + decode paths)
// Selective scan kernel for SSM/Mamba models.
// Auto-generated by scaffoldTs.ts -- do not edit manually.
//
// Naive sequential implementation: correct but not performance-optimized.
// Each work-item handles one channel (d dimension) and scans across all timesteps.
// Parallelism: d_inner work-items run in parallel, each processing seq_len steps sequentially.
//
// Performance note: A Blelloch parallel scan would be faster for long sequences,
// but this sequential version is correct and sufficient for initial porting.
// Use the optimization pipeline (OpenEvolve) to evolve a faster kernel later.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif

// selective_scan: Mamba's core SSM recurrence
// For each channel d:
//   for t in 0..seq_len-1:
//     h[d][s] = exp(A[d][s] * dt[t][d]) * h[d][s] + B[t][s] * dt[t][d] * x[t][d]   for each state s
//     y[t][d] = sum_s(C[t][s] * h[d][s]) + D[d] * x[t][d]
//
// Parameters:
//   x:      [seq_len, d_inner]  — input after conv1d + silu
//   dt:     [seq_len, d_inner]  — delta (time step), after dt_proj + softplus
//   A:      [d_inner, d_state]  — state transition (= -exp(A_log) — already negated by host)
//   B:      [seq_len, d_state]  — input-to-state projection
//   C:      [seq_len, d_state]  — state-to-output projection
//   D:      [d_inner]           — skip connection scalar
//   h:      [d_inner, d_state]  — hidden state (persistent across calls). ALWAYS fp32.
//   y:      [seq_len, d_inner]  — output
//
// FP16 RULE — the recurrent state h is fp32 even when the rest of the model is fp16.
// h is a sequential accumulator: h_t = exp(A·dt)·h_{t-1} + B·dt·x. Storing it as half
// underflows to 0 / saturates to ±Inf within a few timesteps and produces an empty
// transcript. Same rule applies to conv_state in causal_conv1d below.
__kernel void selective_scan(
    __global const storage_t* x,    // [seq_len, d_inner]
    __global const storage_t* dt,   // [seq_len, d_inner]
    __global const storage_t* A,    // [d_inner, d_state]
    __global const storage_t* B,    // [seq_len, d_state]
    __global const storage_t* C,    // [seq_len, d_state]
    __global const storage_t* D,    // [d_inner]
    __global float* h,              // [d_inner, d_state] — read/write state, ALWAYS fp32
    __global storage_t* y,          // [seq_len, d_inner]
    const int seq_len,
    const int d_inner,
    const int d_state) {

    int d = get_global_id(0);  // channel index
    if (d >= d_inner) return;

    float d_val = LOAD(D, d);

    for (int t = 0; t < seq_len; t++) {
        float x_td  = LOAD(x,  t * d_inner + d);
        float dt_td = LOAD(dt, t * d_inner + d);
        float sum_c_h = 0.0f;

        for (int s = 0; s < d_state; s++) {
            int h_idx = d * d_state + s;
            float a_ds = LOAD(A, d * d_state + s);
            float b_ts = LOAD(B, t * d_state + s);
            float c_ts = LOAD(C, t * d_state + s);

            // State update: h = exp(A * dt) * h + B * dt * x   (h is fp32 storage)
            float h_prev = h[h_idx];
            float h_new  = exp(a_ds * dt_td) * h_prev + b_ts * dt_td * x_td;
            h[h_idx] = h_new;

            // Accumulate output: y += C * h
            sum_c_h += c_ts * h_new;
        }

        // Output with skip connection
        STORE(y, t * d_inner + d, sum_c_h + d_val * x_td);
    }
}

// softplus: used to transform dt after projection
// softplus(x) = log(1 + exp(x))
__kernel void softplus(__global storage_t* data, const int n) {
    int gid = get_global_id(0);
    if (gid >= n) return;
    float x = LOAD(data, gid);
    // Numerically stable: for large x, softplus(x) ≈ x
    float v = (x > 20.0f) ? x : log(1.0f + exp(x));
    STORE(data, gid, v);
}

// silu_mul: computes silu(z) * y element-wise (Mamba output gating)
// z and y are [seq_len * d_inner], result stored in y
__kernel void silu_mul(__global const storage_t* z,
                       __global storage_t* y, const int n) {
    int gid = get_global_id(0);
    if (gid >= n) return;
    float z_val = LOAD(z, gid);
    float silu_z = z_val / (1.0f + exp(-z_val));
    float y_val = LOAD(y, gid);
    STORE(y, gid, silu_z * y_val);
}

// mamba2_ssd_scan: Mamba2's selective state-space duality recurrence.
// Reference: model_info/transformers_src/modeling_mamba2.py:Mamba2Mixer.torch_forward
// (the "SSM transformation" branch covering both prefill and decode).
//
// Differences from mamba1's selective_scan above:
//   - A is per-HEAD (shape [num_heads]), not per-channel.
//   - dt is per-(token, head) (shape [seq_len, num_heads]); one dt drives
//     every (head_dim_idx, state_idx) pair in that head.
//   - dt_bias is added and softplus + clamp is applied INSIDE this kernel.
//   - B and C are GROUPED: shape [seq_len, n_groups, state_size], shared
//     across (num_heads/n_groups) heads per group.
//   - D is per-HEAD (shape [num_heads]).
//   - State h has logical shape [num_heads, head_dim, state_size] but we
//     index it flat as [(head*head_dim + chan_in_head) * state_size + s].
//
// One work-item per (head, chan_in_head). Each work-item walks all timesteps
// sequentially (correct per-token state update) and updates state_size states.
//
// FP16 RULE — h is fp32 even when storage_t is half. Recurrent accumulator;
// half storage of h underflows / saturates within a few steps. Same rule as
// mamba1 selective_scan above and causal_conv1d's conv_state.
// VEC4 + dot-reduced version. The s-loop has no s-to-s dependency per channel,
// so it vectorizes cleanly. state_size=128 = 32 vec4. B/C are fp16 (vload_half4),
// h_state stays fp32 (vload4/vstore4). sum_y accumulated via dot(C_v, h_new).
//
// Was 40.7% (1747 µs/call) at Step 0 with scalar inner loop.
// Predicted ≤200 µs/call after vec4 → saves ~1.3 s / 32 tokens.
__kernel void mamba2_ssd_scan(
    __global const storage_t* x,         // [seq_len, intermediate=num_heads*head_dim]
    __global const storage_t* dt_in,     // [seq_len, num_heads]
    __global const storage_t* A_log,     // [num_heads]
    __global const storage_t* dt_bias,   // [num_heads]
    __global const storage_t* B,         // [seq_len, n_groups, state_size]
    __global const storage_t* C,         // [seq_len, n_groups, state_size]
    __global const storage_t* D,         // [num_heads]
    __global float* h_state,             // [num_heads, head_dim, state_size] (fp32)
    __global storage_t* y,               // [seq_len, intermediate]
    const int seq_len,
    const int num_heads,
    const int head_dim,
    const int n_groups,
    const int state_size,
    const float dt_min,
    const float dt_max) {

    int gid = get_global_id(0);
    const int intermediate = num_heads * head_dim;
    if (gid >= intermediate) return;

    int head = gid / head_dim;
    int chan = gid - head * head_dim;
    int heads_per_group = num_heads / n_groups;
    int group = head / heads_per_group;

    float a_log_h = LOAD(A_log, head);
    float a = -exp(a_log_h);
    float d_skip_h = LOAD(D, head);
    float dt_b_h = LOAD(dt_bias, head);

    int x_idx_offset = head * head_dim + chan;        // index within intermediate
    int h_base = (head * head_dim + chan) * state_size; // base into h_state for this channel
    int bc_group_off = group * state_size;             // offset into per-step B/C row

    for (int t = 0; t < seq_len; t++) {
        float dt_raw = LOAD(dt_in, t * num_heads + head);
        float dt_th = dt_raw + dt_b_h;
        dt_th = (dt_th > 20.0f) ? dt_th : log(1.0f + exp(dt_th));
        if (dt_th < dt_min) dt_th = dt_min;
        if (dt_th > dt_max) dt_th = dt_max;

        float dA = exp(a * dt_th);
        float x_th = LOAD(x, t * intermediate + x_idx_offset);

        int bc_row = t * (n_groups * state_size) + bc_group_off;
        float sum_y = 0.0f;

        // Preserve scalar paren grouping ((B*dt)*x) so vec4 reduction is
        // bit-identical to the original scalar version. mamba2's state_size=128
        // and 24-layer recurrence amplify ULP differences much more than
        // mamba1's state_size=16, so any paren reorder visibly changes IDs.
        const int s4_count = state_size >> 2;
#ifdef USE_FP16
        for (int q = 0; q < s4_count; q++) {
            const int s = q * 4;
            float4 B_v = vload_half4(0, B + bc_row + s);
            float4 C_v = vload_half4(0, C + bc_row + s);
            float4 h_prev = vload4(0, h_state + h_base + s);
            // (B * dt_th) * x_th — preserves left-to-right scalar order.
            float4 h_new = (float4)dA * h_prev + B_v * dt_th * x_th;
            vstore4(h_new, 0, h_state + h_base + s);
            // Explicit FMA chain instead of dot() — some Adreno paths run
            // dot() through a lower-precision DSP. Pin to fp32 multiply-add.
            sum_y += C_v.x * h_new.x;
            sum_y += C_v.y * h_new.y;
            sum_y += C_v.z * h_new.z;
            sum_y += C_v.w * h_new.w;
        }
#else
        for (int q = 0; q < s4_count; q++) {
            const int s = q * 4;
            float4 B_v = vload4(0, B + bc_row + s);
            float4 C_v = vload4(0, C + bc_row + s);
            float4 h_prev = vload4(0, h_state + h_base + s);
            float4 h_new = (float4)dA * h_prev + B_v * dt_th * x_th;
            vstore4(h_new, 0, h_state + h_base + s);
            sum_y += C_v.x * h_new.x;
            sum_y += C_v.y * h_new.y;
            sum_y += C_v.z * h_new.z;
            sum_y += C_v.w * h_new.w;
        }
#endif
        for (int s = s4_count * 4; s < state_size; s++) {
            float B_ts = LOAD(B, bc_row + s);
            float C_ts = LOAD(C, bc_row + s);
            float h_prev = h_state[h_base + s];
            float h_new = dA * h_prev + B_ts * dt_th * x_th;
            h_state[h_base + s] = h_new;
            sum_y += C_ts * h_new;
        }

        STORE(y, t * intermediate + x_idx_offset, sum_y + d_skip_h * x_th);
    }
}

// mamba2_ssd_scan_t: transposed-state variant.
//
// h_state stored as [state_size, intermediate] instead of [intermediate, state_size].
// In the original layout, each wave thread (gid space) reads h_state at stride
// `state_size * 4` = 512 bytes — one cache line per thread, 64 cache lines per wave.
// In the transposed layout, wave threads at the same s read consecutive
// addresses (h_state[s*intermediate + gid] for tid 0..63), coalescing into a
// single ~256 byte transaction. 16× fewer cache lines per wave.
//
// Trade: scalar inner loop instead of vec4. The vec4 vload4 in the original
// version reads 4 consecutive states per thread (16 bytes contiguous within
// each thread's row) but those 16 bytes are at stride-512 from neighbor
// threads, so the GPU can't pack them. The transposed scalar inner loop is
// strictly memory-bound at the wave level, and Adreno's coalescer is smart
// about wave-coalesced scalar loads.
//
// FP16 RULE preserved: h_state stays fp32.
// Lever I: h_state can optionally be stored in fp16 (USE_FP16_HSTATE).
// Default: fp32 storage (FP16 RULE — see header comment). Opt-in via host
// build flag -DUSE_FP16_HSTATE for the gemv_m1 program.
#if defined(USE_FP16) && defined(USE_FP16_HSTATE)
  typedef half hstate_t;
  #define HLOAD(p, i)    vload_half((i), (p))
  #define HSTORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float hstate_t;
  #define HLOAD(p, i)    ((p)[(i)])
  #define HSTORE(p, i, v) ((p)[(i)] = (v))
#endif

__kernel void mamba2_ssd_scan_t(
    __global const storage_t* x,
    __global const storage_t* dt_in,
    __global const storage_t* A_log,
    __global const storage_t* dt_bias,
    __global const storage_t* B,
    __global const storage_t* C,
    __global const storage_t* D,
    __global hstate_t* h_state,          // [state_size, intermediate] (transposed)
    __global storage_t* y,
    const int seq_len,
    const int num_heads,
    const int head_dim,
    const int n_groups,
    const int state_size,
    const float dt_min,
    const float dt_max) {

    int gid = get_global_id(0);
    const int intermediate = num_heads * head_dim;
    if (gid >= intermediate) return;

    int head = gid / head_dim;
    int chan = gid - head * head_dim;
    int heads_per_group = num_heads / n_groups;
    int group = head / heads_per_group;

    float a_log_h = LOAD(A_log, head);
    float a = -exp(a_log_h);
    float d_skip_h = LOAD(D, head);
    float dt_b_h = LOAD(dt_bias, head);

    int x_idx_offset = head * head_dim + chan;
    int bc_group_off = group * state_size;

    for (int t = 0; t < seq_len; t++) {
        float dt_raw = LOAD(dt_in, t * num_heads + head);
        float dt_th = dt_raw + dt_b_h;
        dt_th = (dt_th > 20.0f) ? dt_th : log(1.0f + exp(dt_th));
        if (dt_th < dt_min) dt_th = dt_min;
        if (dt_th > dt_max) dt_th = dt_max;

        float dA = exp(a * dt_th);
        float x_th = LOAD(x, t * intermediate + x_idx_offset);
        int bc_row = t * (n_groups * state_size) + bc_group_off;

        float sum_y = 0.0f;
        const float bdx = dt_th * x_th;
        // Manual 8x unroll. Assumes state_size % 8 == 0 (true for 128).
        for (int s = 0; s < state_size; s += 8) {
            const int h0 = (s + 0) * intermediate + gid;
            const int h1 = h0 + intermediate;
            const int h2 = h1 + intermediate;
            const int h3 = h2 + intermediate;
            const int h4 = h3 + intermediate;
            const int h5 = h4 + intermediate;
            const int h6 = h5 + intermediate;
            const int h7 = h6 + intermediate;
            const float B0 = LOAD(B, bc_row + s + 0);
            const float B1 = LOAD(B, bc_row + s + 1);
            const float B2 = LOAD(B, bc_row + s + 2);
            const float B3 = LOAD(B, bc_row + s + 3);
            const float B4 = LOAD(B, bc_row + s + 4);
            const float B5 = LOAD(B, bc_row + s + 5);
            const float B6 = LOAD(B, bc_row + s + 6);
            const float B7 = LOAD(B, bc_row + s + 7);
            const float C0 = LOAD(C, bc_row + s + 0);
            const float C1 = LOAD(C, bc_row + s + 1);
            const float C2 = LOAD(C, bc_row + s + 2);
            const float C3 = LOAD(C, bc_row + s + 3);
            const float C4 = LOAD(C, bc_row + s + 4);
            const float C5 = LOAD(C, bc_row + s + 5);
            const float C6 = LOAD(C, bc_row + s + 6);
            const float C7 = LOAD(C, bc_row + s + 7);
            const float p0 = HLOAD(h_state, h0);
            const float p1 = HLOAD(h_state, h1);
            const float p2 = HLOAD(h_state, h2);
            const float p3 = HLOAD(h_state, h3);
            const float p4 = HLOAD(h_state, h4);
            const float p5 = HLOAD(h_state, h5);
            const float p6 = HLOAD(h_state, h6);
            const float p7 = HLOAD(h_state, h7);
            const float n0 = dA * p0 + B0 * bdx;
            const float n1 = dA * p1 + B1 * bdx;
            const float n2 = dA * p2 + B2 * bdx;
            const float n3 = dA * p3 + B3 * bdx;
            const float n4 = dA * p4 + B4 * bdx;
            const float n5 = dA * p5 + B5 * bdx;
            const float n6 = dA * p6 + B6 * bdx;
            const float n7 = dA * p7 + B7 * bdx;
            HSTORE(h_state, h0, n0);
            HSTORE(h_state, h1, n1);
            HSTORE(h_state, h2, n2);
            HSTORE(h_state, h3, n3);
            HSTORE(h_state, h4, n4);
            HSTORE(h_state, h5, n5);
            HSTORE(h_state, h6, n6);
            HSTORE(h_state, h7, n7);
            sum_y += C0 * n0;
            sum_y += C1 * n1;
            sum_y += C2 * n2;
            sum_y += C3 * n3;
            sum_y += C4 * n4;
            sum_y += C5 * n5;
            sum_y += C6 * n6;
            sum_y += C7 * n7;
        }
        STORE(y, t * intermediate + x_idx_offset, sum_y + d_skip_h * x_th);
    }
}

// mamba2_ssd_scan_coop: cooperative single-wave variant of mamba2_ssd_scan.
// Hardcoded for state_size == 128; host falls back to mamba2_ssd_scan otherwise.
//
// **Single-wave design.** WG_SIZE = 32 (one Adreno A6xx wave at WG-level), each
// thread owns 1 vec4 of the state_size=128 states (32 threads × 4 states = 128).
// All barriers stay intra-wave, which is dramatically cheaper than the
// inter-wave barriers a WG=128 layout would need. (First attempt used WG=128
// with 1 thread per state — measured 902 µs/call vs the original 436 µs scalar
// path. Tree-reduce barriers across 2 waves of the same WG cost more than the
// BW win paid for, so the design is reframed around a single wave.)
//
// **Coalescing argument.** h_state is the dominant traffic per call (~1.5 MB
// per decode token). With 1 WG per (head, chan), all 32 threads in the wave
// hit h_state[h_base + tid*4 .. h_base + tid*4 + 3] — 32 vec4 = 128 contiguous
// fp32 = 512 bytes per WG, contiguous within the wave. Adreno coalesces this
// to ~8 cache-line transactions per wave per load.
//
// **Reduction.** Each thread accumulates a 4-element fp32 partial via vec4
// dot(C_v, h_new). We tree-reduce 32 partials → ls[0] across the wave using
// __local memory + barrier(CLK_LOCAL_MEM_FENCE). Within a single wave, the
// barrier reduces to a wave fence on Adreno (cheap).
//
// **Reduction-order note.** Tree-reduce changes fp32 sum order vs the original
// scalar paren grouping ((B*dt)*x), so token IDs may shift by a few positions.
// Accept new IDs as Step-A reference if drift is coherent (same precedent as
// Step 4+6 GEMV swap).
//
// FP16 RULE preserved: h_state stays fp32.
__kernel __attribute__((reqd_work_group_size(32, 1, 1)))
void mamba2_ssd_scan_coop(
    __global const storage_t* x,         // [seq_len, intermediate=num_heads*head_dim]
    __global const storage_t* dt_in,     // [seq_len, num_heads]
    __global const storage_t* A_log,     // [num_heads]
    __global const storage_t* dt_bias,   // [num_heads]
    __global const storage_t* B,         // [seq_len, n_groups, state_size]
    __global const storage_t* C,         // [seq_len, n_groups, state_size]
    __global const storage_t* D,         // [num_heads]
    __global float* h_state,             // [num_heads, head_dim, state_size] (fp32)
    __global storage_t* y,               // [seq_len, intermediate]
    const int seq_len,
    const int num_heads,
    const int head_dim,
    const int n_groups,
    const int state_size,                // must be 128 (host gates)
    const float dt_min,
    const float dt_max) {

    __local float ls[32];

    const int wg  = get_group_id(0);     // (head * head_dim + chan)
    const int tid = get_local_id(0);     // 0..31, owns vec4 starting at state s = tid*4
    const int intermediate = num_heads * head_dim;
    if (wg >= intermediate) return;

    const int head = wg / head_dim;
    const int chan = wg - head * head_dim;
    const int heads_per_group = num_heads / n_groups;
    const int group = head / heads_per_group;

    const float a_log_h = LOAD(A_log, head);
    const float a       = -exp(a_log_h);
    const float d_skip_h = LOAD(D, head);
    const float dt_b_h   = LOAD(dt_bias, head);

    const int x_idx_offset = head * head_dim + chan;
    const int h_base       = (head * head_dim + chan) * state_size;
    const int bc_group_off = group * state_size;
    const int s            = tid * 4;    // 0, 4, 8, ..., 124

    for (int t = 0; t < seq_len; t++) {
        const float dt_raw = LOAD(dt_in, t * num_heads + head);
        float dt_th = dt_raw + dt_b_h;
        dt_th = (dt_th > 20.0f) ? dt_th : log(1.0f + exp(dt_th));
        if (dt_th < dt_min) dt_th = dt_min;
        if (dt_th > dt_max) dt_th = dt_max;

        const float dA   = exp(a * dt_th);
        const float x_th = LOAD(x, t * intermediate + x_idx_offset);

        const int bc_row = t * (n_groups * state_size) + bc_group_off;

#ifdef USE_FP16
        float4 B_v = vload_half4(0, B + bc_row + s);
        float4 C_v = vload_half4(0, C + bc_row + s);
#else
        float4 B_v = vload4(0, B + bc_row + s);
        float4 C_v = vload4(0, C + bc_row + s);
#endif
        float4 h_prev = vload4(0, h_state + h_base + s);
        float4 h_new  = (float4)dA * h_prev + B_v * dt_th * x_th;
        vstore4(h_new, 0, h_state + h_base + s);

        float partial = 0.0f;
        partial += C_v.x * h_new.x;
        partial += C_v.y * h_new.y;
        partial += C_v.z * h_new.z;
        partial += C_v.w * h_new.w;

        ls[tid] = partial;
        barrier(CLK_LOCAL_MEM_FENCE);

        // Tree-reduce 32 partials → ls[0]. log2(32) = 5 levels, all intra-wave.
        for (int off = 16; off > 0; off >>= 1) {
            if (tid < off) ls[tid] += ls[tid + off];
            barrier(CLK_LOCAL_MEM_FENCE);
        }

        if (tid == 0) {
            STORE(y, t * intermediate + x_idx_offset, ls[0] + d_skip_h * x_th);
        }
    }
}
