// Utility kernels shared across the model.
// Auto-generated by scaffoldTs.ts -- do not edit manually.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif

// ─────────────────────────────────────────────────────────────────────────
// Tiled GEMM: C[M,N] = A[M,K] @ B[K,N], all row-major (OPT#3, razr Adreno620v2).
// Replaces CLBlast in pytorch_conv1d — CLBlast is untuned/pathological on Adreno
// 6xx at the tall-skinny M=70 shapes Bert uses. LDS K-tiling (guide §7.1.2) +
// float4 N register tile (4 accs). MEASURED on razr: a 4×4 16-acc microtile
// REGRESSES 3.5× (register spill) — the repo's >4-acc rule holds for GEMM here
// too. 1-row×4-col is the sweet spot. local = (GN/GTN, GM) = (8, 8) = 64 WIs.
#define GM  8
#define GN  32
#define GK  16
#define GTN 4
__kernel void st_gemm(
    __global const storage_t* A,
    __global const storage_t* B,
    __global storage_t*       C,
    const int M, const int N, const int K) {
#ifdef USE_FP16
    // fp16 half2-packed MAC: 2 output cols per half2 mad instruction (2× ALU) with
    // half LDS (½ LDS traffic). Accumulate within a GK=16 K-chunk in half2, then
    // combine into fp32 (K-split) so long-K precision is preserved. Bert values are
    // bounded, so the per-chunk half sum (≤16 terms) never overflows fp16.
    __local half As[GM][GK];
    __local half Bs[GK][GN];
#else
    __local float As[GM][GK];
    __local float Bs[GK][GN];
#endif
    const int lx = get_local_id(0);
    const int ly = get_local_id(1);
    const int row  = get_group_id(1) * GM + ly;
    const int col0 = get_group_id(0) * GN + lx * GTN;
    const int rowb = get_group_id(1) * GM;
    const int colb = get_group_id(0) * GN;
    const int nthreads = (GN / GTN) * GM;
    const int tid = ly * (GN / GTN) + lx;
    float acc0 = 0.0f, acc1 = 0.0f, acc2 = 0.0f, acc3 = 0.0f;

    for (int k0 = 0; k0 < K; k0 += GK) {
#ifndef USE_FP16
        // Vectorized global→LDS staging: 4 consecutive elements per vload4 → ¼ the
        // load instructions and no per-element div/mod (this kernel is issue-bound
        // on loads). Interior fast path; edges fall back to scalar bounds checks.
        for (int i = tid; i < GM * (GK / 4); i += nthreads) {
            int r = i / (GK / 4), c = (i - r * (GK / 4)) * 4, gr = rowb + r, gc = k0 + c;
            float4 v;
            if (gr < M && gc + 3 < K) v = vload4(0, A + gr * K + gc);
            else { v.x = (gr<M&&gc+0<K)?A[gr*K+gc+0]:0.0f; v.y=(gr<M&&gc+1<K)?A[gr*K+gc+1]:0.0f;
                   v.z = (gr<M&&gc+2<K)?A[gr*K+gc+2]:0.0f; v.w=(gr<M&&gc+3<K)?A[gr*K+gc+3]:0.0f; }
            vstore4(v, 0, &As[r][c]);
        }
        for (int i = tid; i < GK * (GN / 4); i += nthreads) {
            int r = i / (GN / 4), c = (i - r * (GN / 4)) * 4, gr = k0 + r, gc = colb + c;
            float4 v;
            if (gr < K && gc + 3 < N) v = vload4(0, B + gr * N + gc);
            else { v.x = (gr<K&&gc+0<N)?B[gr*N+gc+0]:0.0f; v.y=(gr<K&&gc+1<N)?B[gr*N+gc+1]:0.0f;
                   v.z = (gr<K&&gc+2<N)?B[gr*N+gc+2]:0.0f; v.w=(gr<K&&gc+3<N)?B[gr*N+gc+3]:0.0f; }
            vstore4(v, 0, &Bs[r][c]);
        }
#else
        for (int i = tid; i < GM * GK; i += nthreads) {
            int r = i / GK, c = i - r * GK, gr = rowb + r, gc = k0 + c;
            As[r][c] = (gr < M && gc < K) ? (float)LOAD(A, gr * K + gc) : 0.0f;
        }
        for (int i = tid; i < GK * GN; i += nthreads) {
            int r = i / GN, c = i - r * GN, gr = k0 + r, gc = colb + c;
            Bs[r][c] = (gr < K && gc < N) ? (float)LOAD(B, gr * N + gc) : 0.0f;
        }
#endif
        barrier(CLK_LOCAL_MEM_FENCE);
#ifdef USE_FP16
        half2 h01 = (half2)(0.0h), h23 = (half2)(0.0h);
        for (int kk = 0; kk < GK; kk++) {
            half2 a2 = (half2)(As[ly][kk]);
            half4 bv = vload4(0, &Bs[kk][lx * GTN]);
            h01 = mad(a2, bv.s01, h01);
            h23 = mad(a2, bv.s23, h23);
        }
        acc0 += (float)h01.x; acc1 += (float)h01.y;
        acc2 += (float)h23.x; acc3 += (float)h23.y;
#else
        for (int kk = 0; kk < GK; kk++) {
            float a = As[ly][kk];
            // The 4 output cols read 4 CONSECUTIVE Bs elements → one vload4
            // instead of 4 scalar LDS loads (same LDS-load-bound win as conv1d).
            float4 bv = vload4(0, &Bs[kk][lx * GTN]);
            acc0 = mad(a, bv.x, acc0);
            acc1 = mad(a, bv.y, acc1);
            acc2 = mad(a, bv.z, acc2);
            acc3 = mad(a, bv.w, acc3);
        }
#endif
        barrier(CLK_LOCAL_MEM_FENCE);
    }
    if (row < M) {
        int cbase = row * N + col0;
        if (col0 + 0 < N) STORE(C, cbase + 0, acc0);
        if (col0 + 1 < N) STORE(C, cbase + 1, acc1);
        if (col0 + 2 < N) STORE(C, cbase + 2, acc2);
        if (col0 + 3 < N) STORE(C, cbase + 3, acc3);
    }
}

// Element-wise add: a[i] += b[i]. Operates on activation buffers (storage_t).
// Internal arithmetic in float so fp16 storage doesn't lose precision on
// long residual chains (residual stream variance shrinks otherwise).
__kernel void element_add(__global storage_t* a,
                          __global const storage_t* b,
                          const int n) {
    int gid = get_global_id(0);
    if (gid < n) {
        float av = LOAD(a, gid);
        float bv = LOAD(b, gid);
        STORE(a, gid, av + bv);
    }
}

// Per-row split of a row-major [rows, 2*half] tensor into two contiguous
// [rows, half] tensors. Use this for chunk(2, dim=-1) on GLU/SwiGLU/GeGLU
// gate/up activations — byte-offset sub-buffer splits produce wrong data
// because contiguous bytes span BOTH halves of the first few rows, not
// first-half of every row.
//
// global_work_size = rows * half_cols (one work-item per output element of one half)
// Layout:
//   src[row, col]   = input[row * (2*half_cols) + col]              for col in [0, 2*half_cols)
//   first[row, i]   = input[row * (2*half_cols) + i]                for i in [0, half_cols)
//   second[row, i]  = input[row * (2*half_cols) + i + half_cols]    for i in [0, half_cols)
//
// IMPORTANT — DO NOT rename half_cols to bare 'half'. OpenCL's cl_khr_fp16
// makes 'half' a reserved type token (the fp16 storage type defined by the
// LOAD/STORE preamble). Adreno's clang front-end treats any identifier named
// 'half' as a parse error in this context. Keep the suffix.
__kernel void split_last_dim_2(
    __global const storage_t* src,
    __global storage_t* first,
    __global storage_t* second,
    const int rows,
    const int half_cols) {
    int gid = get_global_id(0);
    const int total = rows * half_cols;
    if (gid >= total) return;
    int row = gid / half_cols;
    int col = gid - row * half_cols;
    int src_base = row * (half_cols * 2);
    float a = LOAD(src, src_base + col);
    float b = LOAD(src, src_base + col + half_cols);
    STORE(first,  row * half_cols + col, a);
    STORE(second, row * half_cols + col, b);
}
