// Reference: model_info/transformers_src/modeling_mamba.py (MambaMixer.slow_forward) — causal conv1d path
// Causal depthwise 1D convolution kernel for SSM/Mamba models.
// Auto-generated by scaffoldTs.ts -- do not edit manually.
//
// Depthwise: each channel is convolved independently (groups = d_inner).
// Causal: only looks at current and past positions (left-padded with state or zeros).
//
// For prompt processing: x is [seq_len, d_inner], state is zeros or previous state.
// For single-token generation: x is [1, d_inner], state is [d_inner, d_conv-1] from previous step.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif

// causal_conv1d: depthwise 1D convolution with causal (left) padding
// Each work-item handles one (t, d) output element.
//
// Parameters:
//   x:         [seq_len, d_inner]         — input
//   weight:    [d_inner, d_conv]           — per-channel conv weights (from mixer.conv1d.weight)
//   bias:      [d_inner]                   — per-channel bias
//   conv_state:[d_inner, d_conv - 1]       — left-padding state (previous timesteps), read/write. ALWAYS fp32.
//   output:    [seq_len, d_inner]          — result
//   seq_len, d_inner, d_conv: dimensions
//
// FP16 RULE — conv_state is fp32 even when the rest of the model is fp16. It carries
// values across token-step boundaries; narrowing through half each step poisons the
// running window after a handful of tokens. Same precision class as selective_scan's h.
__kernel void causal_conv1d(
    __global const storage_t* x,          // [seq_len, d_inner]
    __global const storage_t* weight,     // [d_inner, d_conv]
    __global const storage_t* bias,       // [d_inner]
    __global float* conv_state,           // [d_inner, d_conv - 1] — persistent state, ALWAYS fp32
    __global storage_t* output,           // [seq_len, d_inner]
    const int seq_len,
    const int d_inner,
    const int d_conv) {

    int gid = get_global_id(0);
    int t = gid / d_inner;   // timestep
    int d = gid % d_inner;   // channel
    if (t >= seq_len || d >= d_inner) return;

    int pad = d_conv - 1;  // causal padding length
    float acc = LOAD(bias, d);

    for (int k = 0; k < d_conv; k++) {
        int src_t = t - pad + k;  // position in the combined [state | x] sequence
        float val;
        if (src_t < 0) {
            // Read from conv_state: maps to conv_state[d, pad + src_t]
            int state_idx = d * pad + (pad + src_t);
            val = conv_state[state_idx];
        } else {
            val = LOAD(x, src_t * d_inner + d);
        }
        acc += LOAD(weight, d * d_conv + k) * val;
    }
    // Fused SiLU: x / (1 + exp(-x)). Saves a separate silu_inplace launch
    // per layer per token. NOTE: update_conv_state reads the un-silu'd x
    // (the conv input), not output, so the fusion is safe.
    STORE(output, t * d_inner + d, acc / (1.0f + exp(-acc)));
}

// update_conv_state: after processing a sequence, save the last (d_conv-1) timesteps
// as the new conv_state for the next call.
// Call this AFTER causal_conv1d to update state for incremental generation.
// conv_state is fp32 (recurrent buffer rule — see causal_conv1d above).
__kernel void update_conv_state(
    __global const storage_t* x,        // [seq_len, d_inner] — the input that was just processed
    __global float* conv_state,         // [d_inner, d_conv - 1] — state to update, ALWAYS fp32
    const int seq_len,
    const int d_inner,
    const int d_conv) {

    int d = get_global_id(0);  // channel
    if (d >= d_inner) return;

    int pad = d_conv - 1;
    for (int k = 0; k < pad; k++) {
        int src_t = seq_len - pad + k;
        float val = (src_t >= 0) ? LOAD(x, src_t * d_inner + d) : 0.0f;
        conv_state[d * pad + k] = val;
    }
}

// silu_inplace: applies SiLU activation in-place (used after causal_conv1d)
__kernel void silu_inplace(__global storage_t* data, const int n) {
    int gid = get_global_id(0);
    if (gid >= n) return;
    float x = LOAD(data, gid);
    STORE(data, gid, x / (1.0f + exp(-x)));
}
