// Embedding kernel: token + position embedding lookup.
// Auto-generated by scaffoldTs.ts -- do not edit manually.
// Each work-item handles one sequence position (relative to the dispatch).
//
// start_pos contract: the absolute position of input_ids[0] in the full
// sequence. Prefill passes 0; decode passes the count of tokens already
// processed (prompt_len + decode_step). The wpe lookup uses
// (start_pos + relative_pos); the output buffer is laid out per relative
// position. Without start_pos the decode pass reads wpe[0] for every
// generated token regardless of its absolute position — every post-prefill
// token is then wrong. Required for any model with absolute position
// embeddings (GPT-2, GPT-Neo, OPT, BERT, BART, ...). RoPE-based models
// (Llama, Mistral, Qwen) don't have wpe and apply position info in
// attention's RoPE step instead — for them the agent rewrites this kernel
// to drop the wpe lookup; the start_pos arg can stay for signature
// compatibility (and is harmless when unused).
//
// Uniform storage rule (fp16Standards.ts): wte and wpe are storage_t under
// the active build dtype (half under fp16, float under fp32). The kernel
// reads via LOAD, lifts to fp32 for the add, then STOREs as storage_t.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif

// Cooperative dispatch: 1 WG per sequence position, 64 threads cooperate
// over hidden_size via vec4 fp16. Replaces the original 1-thread-per-row
// scalar loop that clocked 482 µs/call at decode for what should be a
// 1.5 KB row copy (Mamba ports don't use wpe — see Backbone::embed which
// passes a zero-filled wpe; it's still added in case any future scaffold
// needs absolute position embeddings).
//
// Host dispatch: gws = seq_len * 64, lws = 64.
#ifndef WG_SIZE_EMB
#define WG_SIZE_EMB 64
#endif

__kernel __attribute__((reqd_work_group_size(WG_SIZE_EMB, 1, 1)))
void embedding_forward(
    __global const int* token_ids,
    __global const storage_t* wte,
    __global const storage_t* wpe,
    __global storage_t* output,
    int hidden_size,
    int start_pos) {
    const int rel_pos = (int)get_group_id(0);
    const int tid     = (int)get_local_id(0);
    const int abs_pos = rel_pos + start_pos;
    const int tok     = token_ids[rel_pos];
    const int base_tok = tok * hidden_size;
    const int base_wpe = abs_pos * hidden_size;
    const int base_out = rel_pos * hidden_size;

    const int hp      = hidden_size / WG_SIZE_EMB;     // 768/64 = 12 fp16 / thread
    const int h_start = tid * hp;

#ifdef USE_FP16
    // 3 vec4 = 12 fp16 / thread (for hidden_size=768).
    int j = 0;
    #pragma unroll
    for (; j + 3 < hp; j += 4) {
        const int idx = h_start + j;
        float4 t = vload_half4(0, wte + base_tok + idx);
        float4 p = vload_half4(0, wpe + base_wpe + idx);
        vstore_half4(t + p, 0, output + base_out + idx);
    }
    for (; j < hp; ++j) {
        const int idx = h_start + j;
        float v = (float)LOAD(wte, base_tok + idx) + (float)LOAD(wpe, base_wpe + idx);
        STORE(output, base_out + idx, v);
    }
#else
    for (int j = 0; j < hp; ++j) {
        const int idx = h_start + j;
        float v = (float)LOAD(wte, base_tok + idx) + (float)LOAD(wpe, base_wpe + idx);
        STORE(output, base_out + idx, v);
    }
#endif
}
