// Reference: model_info/transformers_src/modeling_mamba.py (MambaMixer.slow_forward) — selective_scan recurrence
// Selective scan kernel for SSM/Mamba models.
// Auto-generated by scaffoldTs.ts -- do not edit manually.
//
// Naive sequential implementation: correct but not performance-optimized.
// Each work-item handles one channel (d dimension) and scans across all timesteps.
// Parallelism: d_inner work-items run in parallel, each processing seq_len steps sequentially.
//
// Performance note: A Blelloch parallel scan would be faster for long sequences,
// but this sequential version is correct and sufficient for initial porting.
// Use the optimization pipeline (OpenEvolve) to evolve a faster kernel later.
// Dtype-template preamble — DO NOT EDIT. Driven by host-side -DNNOPT_USE_FP16.
#ifdef USE_FP16
  #pragma OPENCL EXTENSION cl_khr_fp16 : enable
  typedef half storage_t;
  #define LOAD(p, i)    vload_half((i), (p))
  #define STORE(p, i, v) vstore_half((v), (i), (p))
#else
  typedef float storage_t;
  #define LOAD(p, i)    ((p)[(i)])
  #define STORE(p, i, v) ((p)[(i)] = (v))
#endif

// selective_scan: Mamba's core SSM recurrence
// For each channel d:
//   for t in 0..seq_len-1:
//     h[d][s] = exp(A[d][s] * dt[t][d]) * h[d][s] + B[t][s] * dt[t][d] * x[t][d]   for each state s
//     y[t][d] = sum_s(C[t][s] * h[d][s]) + D[d] * x[t][d]
//
// Parameters:
//   x:      [seq_len, d_inner]  — input after conv1d + silu
//   dt:     [seq_len, d_inner]  — delta (time step), after dt_proj + softplus
//   A:      [d_inner, d_state]  — state transition (= -exp(A_log) — already negated by host)
//   B:      [seq_len, d_state]  — input-to-state projection
//   C:      [seq_len, d_state]  — state-to-output projection
//   D:      [d_inner]           — skip connection scalar
//   h:      [d_inner, d_state]  — hidden state (persistent across calls). ALWAYS fp32.
//   y:      [seq_len, d_inner]  — output
//
// FP16 RULE — the recurrent state h is fp32 even when the rest of the model is fp16.
// h is a sequential accumulator: h_t = exp(A·dt)·h_{t-1} + B·dt·x. Storing it as half
// underflows to 0 / saturates to ±Inf within a few timesteps and produces an empty
// transcript. Same rule applies to conv_state in causal_conv1d below.
__kernel void selective_scan(
    __global const storage_t* x,    // [seq_len, d_inner]
    __global const storage_t* dt,   // [seq_len, d_inner]
    __global const float* A,        // [d_inner, d_state] — ALWAYS fp32 (host expands from A_log)
    __global const storage_t* B,    // [seq_len, d_state]
    __global const storage_t* C,    // [seq_len, d_state]
    __global const storage_t* D,    // [d_inner]
    __global float* h,              // [d_inner, d_state] — read/write state, ALWAYS fp32
    __global storage_t* y,          // [seq_len, d_inner]
    const int seq_len,
    const int d_inner,
    const int d_state) {

    int d = get_global_id(0);  // channel index
    if (d >= d_inner) return;

    // NOTE: PyTorch reference (modeling_mamba.py slow_forward):
    //   A = -exp(A_log)
    //   discrete_A = exp(A * discrete_time_step)
    // The s loop has no s-to-s dependency (each h[d,s] is independent), so it
    // vectorizes cleanly on vec4 boundaries. d_state=16 = 4 vec4 for Mamba-130M.

    float d_val = LOAD(D, d);

    for (int t = 0; t < seq_len; t++) {
        float x_td  = LOAD(x,  t * d_inner + d);
        float dt_td = LOAD(dt, t * d_inner + d);
        float sum_c_h = 0.0f;

        // Vec4 inner loop over d_state. d_state must be divisible by 4 (16 ✓).
        const int n_vec4 = d_state >> 2;
        const int t_state_base = t * d_state;
        const int h_base = d * d_state;

        for (int sv = 0; sv < n_vec4; sv++) {
            const int s_off = sv << 2;
            // A is fp32, [d_inner, d_state] row-major → contiguous along s for fixed d.
            float4 a_v = vload4(sv, A + h_base);
            // h is fp32, same layout.
            float4 h_prev_v = vload4(sv, h + h_base);
#ifdef USE_FP16
            // B, C are fp16, [seq_len, d_state] — contiguous along s for fixed t.
            float4 b_v = vload_half4(sv, B + t_state_base);
            float4 c_v = vload_half4(sv, C + t_state_base);
#else
            float4 b_v = vload4(sv, B + t_state_base);
            float4 c_v = vload4(sv, C + t_state_base);
#endif
            // State update vec4. exp on float4 is a hardware-vector op.
            float4 a_dt_v = a_v * dt_td;
            float4 disc_a = exp(a_dt_v);
            float4 h_new_v = disc_a * h_prev_v + b_v * (dt_td * x_td);
            vstore4(h_new_v, sv, h + h_base);
            sum_c_h += dot(c_v, h_new_v);
        }

        // Scalar tail in case d_state isn't a vec4 multiple (unused at d_state=16
        // but kept so the kernel stays correct for future Mamba variants).
        for (int s = (n_vec4 << 2); s < d_state; s++) {
            int h_idx = h_base + s;
            float a_ds = A[h_idx];
            float b_ts = LOAD(B, t_state_base + s);
            float c_ts = LOAD(C, t_state_base + s);
            float h_prev = h[h_idx];
            float disc_a = exp(a_ds * dt_td);
            float h_new  = disc_a * h_prev + b_ts * dt_td * x_td;
            h[h_idx] = h_new;
            sum_c_h += c_ts * h_new;
        }

        STORE(y, t * d_inner + d, sum_c_h + d_val * x_td);
    }
}

// Fused SSM block: selective_scan + softplus(dt+dt_bias) on read + silu_mul(z) on write.
//
// Replaces the launch chain:
//   bias_add(dt, dt_bias) → softplus(dt) → selective_scan(x, dt, ...) → silu_mul(z, y)
// with a single launch. Saves 3 host-side kernel launches per layer per token
// (24 layers × 3 = 72 launches/token, ~2-3 ms host overhead).
//
// The fp16 reduction order changes vs the unfused path because:
//   - softplus is now applied per-channel inside the t-loop instead of in a
//     separate elementwise pass (still bit-identical math at fp32 precision).
//   - silu_mul is folded into the STORE; it reads z[t,d] once per output write.
// All math stays in fp32 accumulators; ssm_state stays fp32. The exact fp16
// rounding may shift token IDs by a few positions but output stays coherent.
__kernel void selective_scan_fused(
    __global const storage_t* x,        // [seq_len, d_inner]   — post-conv1d, post-silu
    __global const storage_t* dt_raw,   // [seq_len, d_inner]   — post-dt_proj, PRE-bias-add
    __global const storage_t* dt_bias,  // [d_inner]             — broadcast bias
    __global const storage_t* z,        // [seq_len, d_inner]   — gate (pre-silu)
    __global const float* A,            // [d_inner, d_state]   — fp32
    __global const storage_t* B,        // [seq_len, d_state]
    __global const storage_t* C,        // [seq_len, d_state]
    __global const storage_t* D,        // [d_inner]
    __global float* h,                  // [d_inner, d_state]   — fp32 recurrent
    __global storage_t* y,              // [seq_len, d_inner]   — output (silu(z)·y)
    const int seq_len,
    const int d_inner,
    const int d_state) {

    int d = get_global_id(0);
    if (d >= d_inner) return;

    float d_val = LOAD(D, d);
    float dt_b  = LOAD(dt_bias, d);

    for (int t = 0; t < seq_len; t++) {
        float x_td = LOAD(x, t * d_inner + d);

        // Fused softplus(dt_raw + dt_bias). Numerically stable for large x.
        float dt_pre = LOAD(dt_raw, t * d_inner + d) + dt_b;
        float dt_td  = (dt_pre > 20.0f) ? dt_pre : log(1.0f + exp(dt_pre));

        float sum_c_h = 0.0f;
        const int n_vec4 = d_state >> 2;
        const int t_state_base = t * d_state;
        const int h_base = d * d_state;

        for (int sv = 0; sv < n_vec4; sv++) {
            float4 a_v      = vload4(sv, A + h_base);
            float4 h_prev_v = vload4(sv, h + h_base);
#ifdef USE_FP16
            float4 b_v = vload_half4(sv, B + t_state_base);
            float4 c_v = vload_half4(sv, C + t_state_base);
#else
            float4 b_v = vload4(sv, B + t_state_base);
            float4 c_v = vload4(sv, C + t_state_base);
#endif
            float4 a_dt_v  = a_v * dt_td;
            float4 disc_a  = exp(a_dt_v);
            float4 h_new_v = disc_a * h_prev_v + b_v * (dt_td * x_td);
            vstore4(h_new_v, sv, h + h_base);
            sum_c_h += dot(c_v, h_new_v);
        }
        // Scalar tail (unused at d_state=16, kept for forward-compat).
        for (int s = (n_vec4 << 2); s < d_state; s++) {
            int h_idx = h_base + s;
            float a_ds   = A[h_idx];
            float b_ts   = LOAD(B, t_state_base + s);
            float c_ts   = LOAD(C, t_state_base + s);
            float h_prev = h[h_idx];
            float h_new  = exp(a_ds * dt_td) * h_prev + b_ts * dt_td * x_td;
            h[h_idx] = h_new;
            sum_c_h += c_ts * h_new;
        }

        // Pre-silu_mul: y_raw = sum_c_h + D·x
        float y_raw = sum_c_h + d_val * x_td;
        // Fused silu_mul: out = silu(z) * y_raw
        float z_td  = LOAD(z, t * d_inner + d);
        float silu_z = z_td / (1.0f + exp(-z_td));
        STORE(y, t * d_inner + d, silu_z * y_raw);
    }
}

// softplus: used to transform dt after projection
// softplus(x) = log(1 + exp(x))
__kernel void softplus(__global storage_t* data, const int n) {
    int gid = get_global_id(0);
    if (gid >= n) return;
    float x = LOAD(data, gid);
    // Numerically stable: for large x, softplus(x) ≈ x
    float v = (x > 20.0f) ? x : log(1.0f + exp(x));
    STORE(data, gid, v);
}

// silu_mul: computes silu(z) * y element-wise (Mamba output gating)
// z and y are [seq_len * d_inner], result stored in y
__kernel void silu_mul(__global const storage_t* z,
                       __global storage_t* y, const int n) {
    int gid = get_global_id(0);
    if (gid >= n) return;
    float z_val = LOAD(z, gid);
    float silu_z = z_val / (1.0f + exp(-z_val));
    float y_val = LOAD(y, gid);
    STORE(y, gid, silu_z * y_val);
}
